ethereum_rpc = "https://eth-hoodi.g.alchemy.com/v2/EJUCT40R7HcjwK7G9tqwBcU1IpBIyIA3"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.dex-watcher-trap]
path = "out/DEXWatcherTrap.sol/DEXWatcherTrap.json"
response_contract = "0xCAd6850D49beaBb9dD57b50a37d85EaA47C74666"
response_function = "flagWallet(address,string)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0xE228163a45e120B5CE06832D8848bE825B060e9d"]
address = "0x3CA04b40c93FaA262af229Fc3b9D0c59C8e3dfFe"
